# Generated by Django 2.2 on 2021-03-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='recipes.Ingredient', to='recipes.Product', verbose_name='ингредиенты'),
        ),
    ]
