# Generated by Django 2.2 on 2021-03-13 16:30

from django.conf import settings
from django.db import migrations, models

import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorite_by',
            field=models.ManyToManyField(blank=recipes.models.Tag, related_name='fav_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='purchase_by',
            field=models.ManyToManyField(blank=True, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
