# Generated by Django 2.2 on 2021-03-16 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210313_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favorite_by',
            field=models.ManyToManyField(blank=True, related_name='fav_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
